// ── Magazine Template Definitions ────────────────────────────────────────────
// 50 templates × 21 layout types. Each template includes:
//   sampleImages  → shown in preview/browse mode (not in edit mode)
//   sampleTexts   → authentic magazine-style copy shown in preview/browse
//   pages[]       → ordered list of layout IDs for this template's pages

export const CATEGORIES = [
  { id:'photo-book',    label:'Photo Book' },
  { id:'dark-editorial',label:'Dark Editorial' },
  { id:'minimal-bw',   label:'Minimal B&W' },
  { id:'retro',        label:'Retro Vintage' },
  { id:'color-block',  label:'Color Block' },
  { id:'film-noir',    label:'Film Noir' },
  { id:'portfolio',    label:'Studio Portfolio' },
  { id:'nature',       label:'Nature & Travel' },
  { id:'zine',         label:'Zine & Casual' },
  { id:'brutalist',    label:'Brutalist' },
]

// ── Font definitions ──────────────────────────────────────────────────────────
const F = {
  // Google Fonts
  playfair:    "'Playfair Display', 'Didot', Georgia, serif",
  bodoni:      "'Bodoni Moda', 'Playfair Display', Georgia, serif",
  abril:       "'Abril Fatface', Georgia, serif",
  bebas:       "'Bebas Neue', 'Impact', 'Arial Black', sans-serif",
  barlow:      "'Barlow Condensed', 'Oswald', sans-serif",
  cinzel:      "'Cinzel', 'Trajan Pro', Georgia, serif",
  spectral:    "'Spectral', 'Garamond', Georgia, serif",
  montserrat:  "'Montserrat', 'Helvetica Neue', Arial, sans-serif",
  raleway:     "'Raleway', 'Montserrat', 'Helvetica Neue', sans-serif",
  josefin:     "'Josefin Sans', 'Montserrat', 'Helvetica Neue', sans-serif",
  lato:        "'Lato', 'Open Sans', 'Helvetica Neue', sans-serif",
  space:       "'Space Grotesk', 'Montserrat', Arial, sans-serif",
  dmserif:     "'DM Serif Display', 'Playfair Display', Georgia, serif",
  baskerville: "'Libre Baskerville', Georgia, serif",
  cormorant:   "'Cormorant Garamond', 'Garamond', Georgia, serif",
  oswald:      "'Oswald', 'Impact', sans-serif",
  // Local custom fonts
  dominik:     "'Dominik', 'Playfair Display', Georgia, serif",
  mileast:     "'Mileast', 'Playfair Display', Georgia, serif",
  bilderberg:  "'Bilderberg', 'Bodoni Moda', Georgia, serif",
  voyager:     "'MADEVoyager', 'Montserrat', Arial, sans-serif",
  elegist:     "'Elegist', 'Cormorant Garamond', Georgia, serif",
  nevera:      "'Nevera', 'Space Grotesk', Arial, sans-serif",
  agraham:     "'Agraham', 'Bebas Neue', sans-serif",
  transcity:   "'Transcity', 'Bebas Neue', sans-serif",
  priestacy:   "'Priestacy', 'Playfair Display', Georgia, serif",
  gondens:     "'Gondens', 'Abril Fatface', serif",
  armelie:     "'Armelie', 'Dancing Script', cursive",
  cocktail:    "'Cocktail', 'Dancing Script', cursive",
  breathing:   "'Breathing', 'Dancing Script', cursive",
  monaly:      "'Monaly', 'Dancing Script', cursive",
  rockybilly:  "'Rockybilly', 'Impact', sans-serif",
  milker:      "'Milker', 'Josefin Sans', sans-serif",
  purgatory:   "'Purgatory', 'Impact', sans-serif",
  ncl:         "'NCLGasdrifo', 'Bebas Neue', sans-serif",
  primor:      "'PrimorStylish', 'Josefin Sans', sans-serif",
}

// ── Sample image aliases ──────────────────────────────────────────────────────
const S = {
  p1: '/mag-samples/fashion-portrait.jpg',
  p2: '/mag-samples/studio-portrait.jpg',
  p3: '/mag-samples/fitness-portrait.jpg',
  p4: '/mag-samples/vintage-portrait.jpg',
  p5: '/mag-samples/bw-portrait.jpg',
  l1: '/mag-samples/travel-landscape.jpg',
  l2: '/mag-samples/nature.jpg',
  l3: '/mag-samples/cityscape.jpg',
  l4: '/mag-samples/architecture.jpg',
  d1: '/mag-samples/minimal-product.jpg',
  d2: '/mag-samples/food-lifestyle.jpg',
  s1: '/mag-samples/sports.jpg',
}

// ── Default texts (fallback for any layout, any template) ─────────────────────
export const DEFAULT_TEXTS = {
  'cover': {
    title:    'THE FRAME',
    subtitle: 'ISSUE 01 — 2026',
    tagline:  'Where light becomes art',
  },
  'photo-book-cover': {
    title:    'PHOTO BOOK',
    subtitle: 'COLLECTION',
    tagline:  'Ignis lantisest expelece rentiam qui rem et fa sim natia si doloremporit. Cupio disinctio magni dolore.',
  },
  'window-strip': {
    title:    'THE SUBJECT',
    subtitle: 'FEATURE STORY\nISSUE 04',
    body:     'A rising voice in contemporary photography, blending raw emotion with precise technical mastery. Their work challenges the boundary between document and dream.',
  },
  'full-bleed': {
    caption: 'A moment suspended in time — light holds still for no one.',
  },
  'split-left': {
    title: 'THE FRAME',
    body:  'Light bends to the will of those who understand it. Each photograph is a negotiation between shadow and illumination, between what is seen and what is felt by the viewer.',
  },
  'split-right': {
    title: 'GOLDEN HOUR',
    body:  'That final sliver of sunlight transforms everything it touches into something extraordinary. The ordinary world becomes sacred for exactly seventeen minutes each evening.',
  },
  'grid-4': {
    caption: 'THE COLLECTION',
  },
  'grid-6': {
    caption: 'SERIES I — LANDSCAPES',
  },
  'feature-trio': {
    title: 'INTO THE LIGHT',
    body:  'Three images, three moments, one vision. Photography is the art of observation — finding beauty in the unremarkable.',
  },
  'masonry-3': {
    caption: 'SERIES II',
  },
  'quote-page': {
    quote:  'Photography is the story I fail to put into words.',
    author: 'DESTIN SPARKS',
  },
  'text-spread': {
    title: 'BEHIND THE LENS',
    body:  'Every photograph tells the story of a choice. The choice to stop, to look, to see what others pass by. It is the quiet discipline of the observer — patient, precise, perpetually curious about the way light falls on ordinary things and transforms them.',
  },
  'collage-5': {},
  'hero-text': {
    title: 'BOLD VISION',
    body:  'ISSUE 03 — PORTRAIT SERIES',
  },
  'editorial-4': {
    title: 'EDITORIAL EYE',
    body:  'Curated selections from our winter archive',
  },
  'row-3': {
    caption:  'THE COLLECTION',
    subtitle: '2026',
  },
  'row-2': {
    title:   'DIPTYCH',
    caption: 'Two perspectives, one story',
  },
  'catalog-spread': {
    caption: 'Series I — 2026',
  },
  'photo-caption': {
    caption: 'Light holds still for no one — but the camera remembers everything.',
  },
  'portrait-feature': {
    name:  'THE SUBJECT',
    title: 'PORTRAIT SERIES',
    body:  'In the stillness of the studio, every gesture speaks. These portraits excavate the interior life — what is held back, what escapes, what the face reveals in its most unguarded moments.',
  },
  'text-columns': {
    title: 'ON LIGHT',
    body1: 'Photography begins where words fail. It is the discipline of the observer — patient, perpetually curious about the way light falls on ordinary surfaces and transforms them into something worthy of attention.',
    body2: 'The great photographers understood that seeing is not passive. It requires a kind of predatory patience, a willingness to wait for the moment when the world arranges itself into meaning.',
  },
  'arch-cover': {
    subtitle: 'PHOTOGRAPHER',
    name:     'PHOTO\nPORTFOLIO',
    title:    'STUDIO SERIES',
    year:     '2026',
    label:    'PORTFOLIO',
  },
  'grid-top-duo': {},
  'two-stack': {},
  'elegant-portrait': {
    label: 'DEEPAN\'S PORTFOLIO',
    title: 'Street Stories',
    st1: 'The Ancient Ghats', sb1: 'Morning light and shadow along the river, captured with patience.',
    st2: 'Candid Moments',   sb2: 'Isolating subjects within the chaotic beauty of the streets.',
    st3: 'Post-Processing',  sb3: 'Color graded to emphasize the raw, natural tones of the city.',
  },
  'captions-trio': {
    title:  'Great Landscapes',
    body:   'A visual journey through rugged terrain. Exploring high-altitude deserts, barren valleys, and ancient monasteries.',
    cap1:   'Kaza Valley — The rugged terrain stretching into the horizon.',
    cap2:   'Key Monastery — Perched on a hill overlooking the river.',
    cap3:   'Kunzum Pass — Gateway to the pristine high-altitude desert.',
  },
  'retro-diagonal': {
    prefix:   'The',
    title:    'RETRO',
    subtitle: 'VINTAGE MAGAZINE',
  },
  'retro-cols': {
    body1: 'Bold new visual language. Typography became playful, colors saturated, layouts broke free from rigid grids to embrace dynamic composition.',
    body2: 'As technology evolved, so did the aesthetic. The mid-century modern movement influenced everything from architecture to print design.',
  },
  'bold-dark': {
    tag:   'ABOUT',
    title: 'DESIGN PROCESS',
    body:  'The creative process begins with a vision — understanding the core essence and stripping away the unnecessary to reveal pure form and emotion. Every project is a new journey.',
  },
  'bold-cover': {
    title:    'PORTFOLIO',
    year:     '2 0 2 5',
    subtitle: 'THE ART\nBEHIND\nTHE VISION',
    name:     'IEM\nPHOTO\nCLUB',
  },
  'triple-portrait': {
    label: 'PHOTOGRAPHY\nPRODUCTION\nCREATIVE\nDIRECTION',
    title: 'Modern Fashion',
  },
  'vintage-collage': {
    prefix: 'The old',
    title:  'MEMORIES',
    body:   'Looking back through these pages brings a rush of emotion. Every photograph is a frozen second in time, holding stories that words can scarcely describe.',
    year:   '2026',
  },
  'constructivist-red': {
    title:    'IEM PHOTO\nCLUB',
    subtitle: 'ISSUE 01 · JANUARY 2026',
    menu1: 'PHOTOGRAPHY',
    menu2: 'EDITORIAL',
    menu3: 'COLLECTION',
    tagline:  'UNLEASH\nTHE FRAME',
  },
  'pillars-toc': {
    label:   'CONTENTS',
    heading: 'INDEX',
    lbl1:    'PORTRAIT\nSERIES',
    lbl2:    'LANDSCAPE\nEDITION',
    lbl3:    'EDITORIAL\nWORK',
  },
  'interview-duo': {
    name:     'THE\nPHOTO\nGRAPHER',
    subtitle: 'FEATURE STORY · ISSUE 04',
  },
  'journal-photo': {
    label: 'A LOOK BACK',
    title: 'Cherished Times',
    body:  'Looking back through these pages brings a rush of emotion. Every photograph is a frozen second in time, holding stories that words can scarcely describe.',
  },
  'scatter-3': {
    title:    'Family',
    subtitle: 'BONDS',
    year:     '2026',
  },
  'lifestyle-cover': {
    bg_title: 'MAGAZINE',
    name:     'POWER',
    subtitle: 'LIFE OF',
    label1:   'EXCLUSIVE\nINTERVIEW\nFEATURE',
    body1:    'An exclusive look inside the world of the contemporary photographer. What drives the creative mind in the digital age?',
  },
  'toc-numbered': {
    title:  'CONTENT',
    item1:  'ABOUT',
    item2:  'CLASSIC PORTRAITS',
    item3:  'LIFESTYLE',
    item4:  'EDITORIAL SHOTS',
  },
}

// ══════════════════════════════════════════════════════════════════════════════
// TEMPLATES (50 total)
// ══════════════════════════════════════════════════════════════════════════════

export const TEMPLATES = [

  // ══════════ PHOTO BOOK ═══════════════════════════════════════════════════════
  // Clean white editorial — lots of photos in grids, serif headings

  {
    id:'pb-01', name:'Desert Landscapes', category:'photo-book',
    colors:{ bg:'#ffffff', surface:'#f0ede8', text:'#1a1a1a', accent:'#1a1a1a', muted:'#888' },
    fonts:{ heading:F.playfair, body:F.lato },
    pages:['photo-book-cover','grid-top-duo','captions-trio','row-2','full-bleed','two-stack','photo-caption'],
    coverStyle:{ titleSize:'3.4rem', layout:'center', accentBar:false, letterSpacing:'-0.025em' },
    sampleImages:{ img1:S.l1, img2:S.l2, img3:S.l4, img4:S.l3, img5:S.l1, img6:S.l2 },
    sampleTexts:{
      title:'PHOTO BOOK', subtitle:'TRAVEL SERIES', tagline:'Observations from the wild — light filtered through canopy, water over stone, sky at the edge of weather',
      caption:'The Desert Collection — 2026',
      cap1:'Spiti Valley — The rugged terrain stretching into the horizon.',
      cap2:'Key Monastery — Perched on a hill overlooking the river.',
      cap3:'Kunzum Pass — Gateway to the pristine high-altitude desert.',
    },
  },
  {
    id:'pb-02', name:'Urban Architecture', category:'photo-book',
    colors:{ bg:'#fafafa', surface:'#ebebeb', text:'#111', accent:'#222', muted:'#999' },
    fonts:{ heading:F.josefin, body:F.raleway },
    pages:['photo-book-cover','grid-top-duo','two-stack','grid-4','full-bleed','row-2'],
    coverStyle:{ titleSize:'3.8rem', layout:'center', accentBar:false, letterSpacing:'0.08em', titleStyle:'normal' },
    sampleImages:{ img1:S.l4, img2:S.l3, img3:S.l4, img4:S.l1, img5:S.l2, img6:S.l3 },
    sampleTexts:{
      title:'ARCHITECTURE', subtitle:'URBAN STUDY', tagline:'A study of form, light and shadow through the built environment of modern cities',
      caption:'Urban Forms — Series II',
    },
  },
  {
    id:'pb-03', name:'Portrait Collection', category:'photo-book',
    colors:{ bg:'#fdf9f4', surface:'#eee9e0', text:'#1a1a1a', accent:'#8b6f4e', muted:'#999' },
    fonts:{ heading:F.bodoni, body:F.baskerville },
    pages:['photo-book-cover','elegant-portrait','grid-top-duo','masonry-3','quote-page','two-stack'],
    coverStyle:{ titleSize:'3rem', layout:'center', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.p1, img2:S.p2, img3:S.p4, img4:S.p5, img5:S.p1, img6:S.p3 },
    sampleTexts:{
      title:'PORTRAIT\nCOLLECTION', subtitle:'STUDIO SERIES', tagline:'An intimate study of the human face — expressions captured in stillness',
      label:'Portrait Collection', name:'ELENA VASQUEZ', title2:'STUDIO PORTRAIT',
      body:'A rising figure in contemporary portrait photography. Her work strips away artifice to reveal something raw and essential.',
      st1:'The Sitting', sb1:'An hour in the studio reveals more than years of acquaintance.',
      st2:'Natural Light', sb2:'Morning window light — no modifier, no reflector, just the sun.',
      st3:'Post-Processing', sb3:'Minimal retouching. The face deserves its truth.',
      quote:'The face is a landscape. Every line tells a story of weather endured.',
      author:'ELENA VASQUEZ',
    },
  },
  {
    id:'pb-04', name:'Nature Journal', category:'photo-book',
    colors:{ bg:'#f7f4ee', surface:'#e8e3d8', text:'#2a2a1a', accent:'#5c6b3a', muted:'#888' },
    fonts:{ heading:F.cormorant, body:F.spectral },
    pages:['photo-book-cover','full-bleed','captions-trio','text-spread','grid-top-duo','photo-caption'],
    coverStyle:{ titleSize:'3.5rem', layout:'center', titleStyle:'italic', accentBar:false },
    sampleImages:{ img1:S.l2, img2:S.l1, img3:S.l2, img4:S.l4, img5:S.l3, img6:S.l2 },
    sampleTexts:{
      title:'NATURE\nJOURNAL', subtitle:'FIELD NOTES', tagline:'Observations from the wild — light filtered through canopy, water over stone, sky at the edge of weather',
      caption:'The world breathes when we stop to listen — photographed across six continents',
      cap1:'Forest floor — morning mist rising from the earth.',
      cap2:'Canopy light — fifty metres up, a separate world.',
      cap3:'River stones — time made visible.',
      title2:'THE FOREST HOUR', body:'Forests teach patience. You cannot rush the light.',
    },
  },
  {
    id:'pb-05', name:'Minimalist Study', category:'photo-book',
    colors:{ bg:'#ffffff', surface:'#f4f4f4', text:'#111', accent:'#333', muted:'#bbb' },
    fonts:{ heading:F.mileast, body:F.josefin },
    pages:['photo-book-cover','grid-top-duo','grid-6','two-stack','full-bleed','editorial-4'],
    coverStyle:{ titleSize:'3.2rem', layout:'center', letterSpacing:'0.1em', accentBar:false },
    sampleImages:{ img1:S.d1, img2:S.d2, img3:S.d1, img4:S.l4, img5:S.l1, img6:S.l3 },
    sampleTexts:{
      title:'MINIMAL', subtitle:'OBJECT STUDY', tagline:'Form distilled to its essence. Photography as reduction — removing everything but the necessary.',
      caption:'Objects in stillness',
    },
  },

  // ══════════ DARK EDITORIAL ═══════════════════════════════════════════════════

  {
    id:'de-01', name:'Shadow Cast', category:'dark-editorial',
    colors:{ bg:'#080808', surface:'#181818', text:'#f0f0f0', accent:'#dc2626', muted:'#666' },
    fonts:{ heading:F.bilderberg, body:F.lato },
    pages:['bold-cover','window-strip','bold-dark','text-spread','grid-4','quote-page'],
    coverStyle:{ titleSize:'4.5rem', layout:'bottom-left', accentBar:true, titleStyle:'italic' },
    sampleImages:{ img1:S.p5, img2:S.p2, img3:S.p1, img4:S.p4 },
    sampleTexts:{
      title:'SHADOW\nCAST', subtitle:'DARK EDITION — NO. 07', tagline:'Into the depths of visible darkness',
      name:'MARCUS GREY', title2:'COVER STORY', body:'His portraits operate in the space between seen and unseen — high contrast, brutal honesty, images that refuse comfortable interpretation.',
      quote:'Darkness is not the absence of light. It is the presence of something else entirely.',
      author:'MARCUS GREY',
    },
  },
  {
    id:'de-02', name:'Eclipse', category:'dark-editorial',
    colors:{ bg:'#0d0d0d', surface:'#1a1a1a', text:'#f5f5f5', accent:'#d4a017', muted:'#555' },
    fonts:{ heading:F.dominik, body:F.montserrat },
    pages:['bold-cover','full-bleed','bold-dark','masonry-3','text-spread','editorial-4'],
    coverStyle:{ titleSize:'5rem', layout:'bottom-left', accentBar:true, letterSpacing:'-0.02em' },
    sampleImages:{ img1:S.p1, img2:S.p5, img3:S.p2, img4:S.p3 },
    sampleTexts:{
      title:'ECLIPSE', subtitle:'EDITORIAL — ISSUE 12', tagline:'Light swallowed whole',
      caption:'Between the light and the dark, the image lives',
      name:'DIANA SOLEIL', title2:'GOLDEN HOUR FEATURE', body:'Working entirely in natural light, she finds the moments just before darkness — when gold bleeds into shadow and every surface becomes a painting.',
    },
  },
  {
    id:'de-03', name:'Midnight Blue', category:'dark-editorial',
    colors:{ bg:'#06080f', surface:'#0e1220', text:'#e8eaf6', accent:'#4f80f0', muted:'#4a4f6a' },
    fonts:{ heading:F.mileast, body:F.raleway },
    pages:['bold-cover','full-bleed','split-right','window-strip','quote-page','editorial-4'],
    coverStyle:{ titleSize:'4.2rem', layout:'bottom-right', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.l3, img2:S.p5, img3:S.p1, img4:S.l4 },
    sampleTexts:{
      title:'MIDNIGHT', subtitle:'URBAN NOIR — VOL III', tagline:'The city never truly sleeps',
      caption:'Streets at 3am hold a different kind of honesty',
      quote:'Cities are most beautiful when everyone else has gone to sleep.',
      author:'ANONYMOUS',
    },
  },
  {
    id:'de-04', name:'Phantom', category:'dark-editorial',
    colors:{ bg:'#0a0008', surface:'#160a14', text:'#f5eff5', accent:'#9b59b6', muted:'#5a4560' },
    fonts:{ heading:F.nevera, body:F.josefin },
    pages:['bold-cover','window-strip','bold-dark','feature-trio','full-bleed','text-columns'],
    coverStyle:{ titleSize:'5rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.02em' },
    sampleImages:{ img1:S.p4, img2:S.p5, img3:S.p2, img4:S.p1 },
    sampleTexts:{
      title:'PHANTOM', subtitle:'NOCTURNE SERIES', tagline:'Shadows with names',
      caption:'The camera sees what the eye refuses',
      body1:'Phantom photographs the invisible — the weight of a glance, the residue of movement, the emotion that lingers after the subject has left the frame.',
      body2:'Her work asks us to look again. What did we miss the first time? What have we been trained not to see?',
    },
  },
  {
    id:'de-05', name:'Noir Feature', category:'dark-editorial',
    colors:{ bg:'#111111', surface:'#1e1e1e', text:'#e0d8d0', accent:'#c0a070', muted:'#666' },
    fonts:{ heading:F.priestacy, body:F.spectral },
    pages:['cover','window-strip','portrait-feature','text-columns','quote-page','full-bleed'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.p2, img2:S.p5, img3:S.p4, img4:S.p1 },
    sampleTexts:{
      title:'NOIR\nFEATURE', subtitle:'THE INTERVIEW ISSUE', tagline:'Conversations in low light',
      name:'JAMES CARTER', title2:'IN FOCUS', body:'Twenty years behind the lens, Carter has documented everything from war zones to fashion weeks. What he sees in every frame is the same thing: the weight of being human.',
      quote:'I never take a photograph. I receive it.',
      author:'JAMES CARTER',
    },
  },

  // ══════════ MINIMAL B&W ══════════════════════════════════════════════════════

  {
    id:'mb-01', name:'Vogue Mono', category:'minimal-bw',
    colors:{ bg:'#ffffff', surface:'#f2f2f2', text:'#0a0a0a', accent:'#0a0a0a', muted:'#888' },
    fonts:{ heading:F.bodoni, body:F.lato },
    pages:['cover','full-bleed','split-left','grid-4','editorial-4','quote-page'],
    coverStyle:{ titleSize:'5rem', layout:'bottom-left', accentBar:true, titleStyle:'italic' },
    sampleImages:{ img1:S.p1, img2:S.p5, img3:S.p2, img4:S.p4 },
    sampleTexts:{
      title:'VOGUE\nMONO', subtitle:'WINTER ISSUE', tagline:'Fashion distilled to its essence',
      caption:'The white space says everything the image cannot',
      title2:'CLEAN LINES', body:'The best fashion photography removes everything that is not the subject. What remains must be absolute.',
      quote:'Elegance is not about being noticed, it is about being remembered.',
      author:'GIORGIO ARMANI',
    },
  },
  {
    id:'mb-02', name:'Studio White', category:'minimal-bw',
    colors:{ bg:'#fafafa', surface:'#e8e8e8', text:'#111', accent:'#333', muted:'#999' },
    fonts:{ heading:F.raleway, body:F.lato },
    pages:['cover','split-right','grid-6','feature-trio','text-spread','full-bleed'],
    coverStyle:{ titleSize:'3.8rem', layout:'center', accentBar:false, letterSpacing:'0.35em' },
    sampleImages:{ img1:S.p2, img2:S.p5, img3:S.p1, img4:S.p4, img5:S.p3, img6:S.d1 },
    sampleTexts:{
      title:'STUDIO\nWHITE', subtitle:'PORTRAIT ISSUE', tagline:'Six photographers. One studio. Zero compromise.',
      title2:'THE STUDIO', body:'A room stripped of everything extraneous. A single light source. A subject who cannot hide. This is where truth lives.',
    },
  },
  {
    id:'mb-03', name:'Editorial Serif', category:'minimal-bw',
    colors:{ bg:'#f5f0e8', surface:'#e4ddd0', text:'#1a1a1a', accent:'#1a1a1a', muted:'#888' },
    fonts:{ heading:F.playfair, body:F.baskerville },
    pages:['cover','full-bleed','masonry-3','split-left','editorial-4','quote-page'],
    coverStyle:{ titleSize:'4.2rem', layout:'top-right', accentBar:true, titleStyle:'italic' },
    sampleImages:{ img1:S.p4, img2:S.p5, img3:S.p2, img4:S.p1 },
    sampleTexts:{
      title:'EDITORIAL', subtitle:'AUTUMN COLLECTION', tagline:'The season of beautiful decay',
      caption:'Shot on 35mm film, Tuscany',
      title2:'OLD LIGHT', body:'The warmth of autumn afternoon light does something to a photograph that no filter can replicate — it gives everything it touches the quality of memory.',
      quote:'In photography, there is a reality so subtle that it becomes more real than reality.',
      author:'ALFRED STIEGLITZ',
    },
  },
  {
    id:'mb-04', name:'Paper Thin', category:'minimal-bw',
    colors:{ bg:'#ffffff', surface:'#f8f8f8', text:'#222', accent:'#555', muted:'#bbb' },
    fonts:{ heading:F.josefin, body:F.raleway },
    pages:['cover','grid-4','split-right','full-bleed','text-spread','feature-trio'],
    coverStyle:{ titleSize:'4.5rem', layout:'bottom-right', accentBar:false, letterSpacing:'0.3em' },
    sampleImages:{ img1:S.p5, img2:S.p1, img3:S.p2, img4:S.p4 },
    sampleTexts:{
      title:'PAPER\nTHIN', subtitle:'MINIMALIST EDITION', tagline:'Less is everything',
      title2:'REDUCTION', body:'Strip the image down to its essential elements. Remove one more thing. Then look again. This is the practice of the minimalist photographer.',
    },
  },
  {
    id:'mb-05', name:'Ivory Grid', category:'minimal-bw',
    colors:{ bg:'#fdf9f3', surface:'#ede9e0', text:'#2a2a2a', accent:'#333', muted:'#999' },
    fonts:{ heading:F.cormorant, body:F.lato },
    pages:['cover','masonry-3','full-bleed','editorial-4','grid-6','quote-page'],
    coverStyle:{ titleSize:'3.8rem', layout:'center', accentBar:true, titleStyle:'italic' },
    sampleImages:{ img1:S.p4, img2:S.p2, img3:S.p5, img4:S.p1, img5:S.d1, img6:S.l4 },
    sampleTexts:{
      title:'IVORY\nGRID', subtitle:'CURATED COLLECTION', tagline:'Six works. One vision.',
      quote:'The grid is a meditation. Each frame a breath.',
      author:'CAROLINA REYES',
    },
  },

  // ══════════ RETRO VINTAGE ════════════════════════════════════════════════════

  {
    id:'rv-01', name:'Golden Age', category:'retro',
    colors:{ bg:'#e6e6e6', surface:'#333333', text:'#333333', accent:'#d4a017', muted:'#888' },
    fonts:{ heading:F.playfair, body:F.spectral },
    pages:['vintage-collage','journal-photo','scatter-3','quote-page','editorial-4','feature-trio'],
    coverStyle:{ titleSize:'4.5rem', layout:'bottom-left', accentBar:true },
    sampleImages:{ img1:S.p4, img2:S.p3, img3:S.p5, img4:S.p2 },
    sampleTexts:{
      title:'GOLDEN\nAGE', subtitle:'VINTAGE EDITION — 1972', tagline:'When photography was an act of faith',
      caption:'Shot on Kodachrome — never fades, never forgets',
      title2:'THE GRAIN', body:'Grain is not a flaw. It is evidence of the light actually touching the film — chemistry, not mathematics. The imperfection is the proof.',
      quote:'You don\'t take a photograph, you make it.',
      author:'ANSEL ADAMS',
    },
  },
  {
    id:'rv-02', name:'Sepia Dreams', category:'retro',
    colors:{ bg:'#f0ebe0', surface:'#333', text:'#2a1a0a', accent:'#a06030', muted:'#806040' },
    fonts:{ heading:F.playfair, body:F.spectral },
    pages:['vintage-collage','journal-photo','scatter-3','masonry-3','text-spread','quote-page'],
    coverStyle:{ titleSize:'5rem', layout:'bottom-left', accentBar:false, letterSpacing:'0.05em' },
    sampleImages:{ img1:S.p4, img2:S.l1, img3:S.p5, img4:S.l2 },
    sampleTexts:{
      title:'SEPIA\nDREAMS', subtitle:'ARCHIVE COLLECTION', tagline:'From the darkroom, with love',
      caption:'Every photograph is a certificate of presence — ROLAND BARTHES',
      title2:'MEMORY', body:'Sepia is the color of memory. Not because things were sepia — they were not — but because we associate that warmth with time passed and meaning accumulated.',
    },
  },
  {
    id:'rv-03', name:'Vintage Press', category:'retro',
    colors:{ bg:'#f5e8c0', surface:'#2a6060', text:'#2a1a00', accent:'#8b2020', muted:'#806040' },
    fonts:{ heading:F.abril, body:F.baskerville },
    pages:['retro-diagonal','retro-cols','split-left','full-bleed','editorial-4','text-spread'],
    coverStyle:{ titleSize:'5.5rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.05em' },
    sampleImages:{ img1:S.p3, img2:S.p4, img3:S.s1, img4:S.p5 },
    sampleTexts:{
      title:'VINTAGE\nPRESS', subtitle:'SPORTS & CULTURE — 1968', tagline:'The athletes who moved history',
      caption:'From the archive — unretouched originals',
      title2:'THE RECORD', body:'Before digital, before the pixel, before infinite storage — there was one shot, one roll, one chance to capture what no one else would see again.',
    },
  },
  {
    id:'rv-04', name:'Film Roll', category:'retro',
    colors:{ bg:'#e2c792', surface:'#386060', text:'#2c2825', accent:'#c0610a', muted:'#666048' },
    fonts:{ heading:F.abril, body:F.baskerville },
    pages:['retro-diagonal','retro-cols','portrait-feature','grid-4','quote-page','text-spread'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:true },
    sampleImages:{ img1:S.p4, img2:S.p5, img3:S.p2, img4:S.p3 },
    sampleTexts:{
      title:'FILM\nROLL', subtitle:'ANALOG EDITION', tagline:'36 exposures. No do-overs.',
      name:'RAY MORROW', title2:'ANALOG PORTRAITS', body:'Morrow shoots only on film. "Digital is perfect," he says. "Film is true." There\'s a difference.',
      quote:'Film is silver and gelatin and light. It is the most honest medium.',
      author:'RAY MORROW',
    },
  },
  {
    id:'rv-05', name:'Postcard', category:'retro',
    colors:{ bg:'#f5f0e4', surface:'#2a8a7a', text:'#2a1a0a', accent:'#a02020', muted:'#8a7060' },
    fonts:{ heading:F.playfair, body:F.baskerville },
    pages:['retro-diagonal','retro-cols','row-3','full-bleed','text-columns','quote-page'],
    coverStyle:{ titleSize:'3.5rem', layout:'top-left', accentBar:true, titleStyle:'italic' },
    sampleImages:{ img1:S.l1, img2:S.l2, img3:S.l4, img4:S.l3 },
    sampleTexts:{
      title:'WISH YOU\nWERE HERE', subtitle:'TRAVEL EDITION', tagline:'Photographs from places you\'ve never been',
      caption:'Greetings from somewhere beautiful',
      title2:'DISTANCE', body:'The postcard photograph says: look where I am. Look what exists in the world that you haven\'t seen yet. Come.',
      quote:'The world is a book, and those who do not travel read only one page.',
      author:'SAINT AUGUSTINE',
    },
  },

  // ══════════ COLOR BLOCK ══════════════════════════════════════════════════════

  {
    id:'cb-01', name:'Flame Orange', category:'color-block',
    colors:{ bg:'#0d0d0d', surface:'#1a1a1a', text:'#ffffff', accent:'#ff5a1f', muted:'#666' },
    fonts:{ heading:F.oswald, body:F.montserrat },
    pages:['constructivist-red','pillars-toc','interview-duo','grid-4','text-spread','full-bleed'],
    coverStyle:{ titleSize:'5.5rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.04em' },
    sampleImages:{ img1:S.p3, img2:S.s1, img3:S.p1, img4:S.p5 },
    sampleTexts:{
      title:'WAKE UP.\nWORK OUT.\nREPEAT.', subtitle:'FITNESS EDITION — NO. 08', tagline:'12 weeks to transform your body',
      name:'ALEX POWERS', title2:'COVER ATHLETE', body:'At 23, Powers became the youngest athlete to win back-to-back championships. This is the story of what happened next — and why the hardest challenge came after the victory.',
      caption:'Train like your life depends on it. It does.',
    },
  },
  {
    id:'cb-02', name:'Cobalt', category:'color-block',
    colors:{ bg:'#040d1a', surface:'#081428', text:'#f0f8ff', accent:'#2563eb', muted:'#4a6080' },
    fonts:{ heading:F.barlow, body:F.josefin },
    pages:['lifestyle-cover','toc-numbered','split-left','grid-4','hero-text','quote-page'],
    coverStyle:{ titleSize:'5rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.05em' },
    sampleImages:{ img1:S.l3, img2:S.l4, img3:S.p5, img4:S.l1 },
    sampleTexts:{
      title:'COBALT\nCITY', subtitle:'URBAN SERIES — VOLUME II', tagline:'Steel, glass and the blue hour',
      caption:'Architecture is frozen music — SCHOPENHAUER',
      title2:'CITY FORM', body:'URBAN ARCHITECTURE AT DUSK',
      quote:'We shape our buildings, and afterwards our buildings shape us.',
      author:'WINSTON CHURCHILL',
    },
  },
  {
    id:'cb-03', name:'Emerald', category:'color-block',
    colors:{ bg:'#04120a', surface:'#081a0f', text:'#e8f5ee', accent:'#16a34a', muted:'#3d6e4e' },
    fonts:{ heading:F.cinzel, body:F.spectral },
    pages:['cover','full-bleed','split-right','masonry-3','text-spread','editorial-4'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:true },
    sampleImages:{ img1:S.l2, img2:S.l1, img3:S.l4, img4:S.l3 },
    sampleTexts:{
      title:'EMERALD', subtitle:'NATURE ISSUE — SPRING', tagline:'Into the green world',
      caption:'A forest breathes. Do you?',
      title2:'THE CANOPY', body:'Above the forest floor, fifty metres up, exists an entirely separate world. A world of light and wind and creatures that have never touched the ground.',
    },
  },
  {
    id:'cb-04', name:'Scarlet', category:'color-block',
    colors:{ bg:'#0d0000', surface:'#1a0000', text:'#fff0f0', accent:'#dc2626', muted:'#663333' },
    fonts:{ heading:F.oswald, body:F.lato },
    pages:['constructivist-red','pillars-toc','interview-duo','grid-4','editorial-4','quote-page'],
    coverStyle:{ titleSize:'5.5rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.03em' },
    sampleImages:{ img1:S.p1, img2:S.p5, img3:S.p4, img4:S.p2 },
    sampleTexts:{
      title:'SCARLET', subtitle:'FASHION WEEK — PARIS', tagline:'Red is not a color. It is an emotion.',
      caption:'Collection automne / hiver',
      name:'ROUGE', title2:'THE RED ISSUE', body:'This season, the only color that matters. Designers returned again and again to red — not as accent but as statement, as manifesto, as refusal to be ignored.',
      quote:'I have a special relationship with red. It is the color of life.',
      author:'YVES SAINT LAURENT',
    },
  },
  {
    id:'cb-05', name:'Citrus', category:'color-block',
    colors:{ bg:'#0d0c00', surface:'#1a1800', text:'#fffce8', accent:'#eab308', muted:'#666440' },
    fonts:{ heading:F.agraham, body:F.montserrat },
    pages:['cover','full-bleed','split-left','feature-trio','text-columns','quote-page'],
    coverStyle:{ titleSize:'5rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.05em' },
    sampleImages:{ img1:S.d2, img2:S.d1, img3:S.p1, img4:S.l1 },
    sampleTexts:{
      title:'CITRUS', subtitle:'FOOD & LIFESTYLE', tagline:'Taste. Eat. Photograph. Repeat.',
      caption:'The kitchen is a studio. Every plate is a canvas.',
      body1:'Food photography is an act of translation — taking something that exists in time (a warm dish, steam rising, a fleeting moment of perfect presentation) and fixing it in space.',
      body2:'The best food photographs make you hungry. The great ones make you feel something you cannot name — nostalgia, desire, an ache for something beyond the image.',
    },
  },

  // ══════════ FILM NOIR ════════════════════════════════════════════════════════

  {
    id:'fn-01', name:'Smoke & Mirrors', category:'film-noir',
    colors:{ bg:'#0a0a0a', surface:'#181818', text:'#d8d8d8', accent:'#888', muted:'#555' },
    fonts:{ heading:F.cormorant, body:F.spectral },
    pages:['cover','full-bleed','split-left','quote-page','editorial-4','text-columns'],
    coverStyle:{ titleSize:'4.2rem', layout:'bottom-left', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.p5, img2:S.p2, img3:S.p4, img4:S.p1 },
    sampleTexts:{
      title:'SMOKE &\nMIRRORS', subtitle:'NOIR EDITION', tagline:'Nothing is what it appears',
      caption:'Seen through cigarette smoke and rain',
      title2:'THE DETECTIVE\'S EYE', body:'Film noir taught us that shadows have their own logic. That what is hidden is more interesting than what is shown. The best photographers never forgot this lesson.',
      body1:'The noir photograph deals in mood, not information. It tells you how something feels before it tells you what something is.',
      body2:'In the shadows between streetlights, in the blur of rain on glass, the camera finds a truth that direct illumination destroys.',
    },
  },
  {
    id:'fn-02', name:'Detective\'s Eye', category:'film-noir',
    colors:{ bg:'#080808', surface:'#141414', text:'#cccccc', accent:'#666', muted:'#444' },
    fonts:{ heading:F.dmserif, body:F.baskerville },
    pages:['cover','window-strip','portrait-feature','full-bleed','text-spread','quote-page'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.p2, img2:S.p5, img3:S.p4, img4:S.l3 },
    sampleTexts:{
      title:'THE\nDETECTIVE\'S\nEYE', subtitle:'CRIME & PHOTOGRAPHY', tagline:'Everyone is a suspect in the right light',
      name:'RAYMOND CROSS', title2:'IN DEPTH', body:'Twenty years photographing crime scenes taught Cross something that art school never could: the image doesn\'t lie, but it only ever tells part of the story.',
      quote:'The camera is an instrument that teaches people how to see without a camera.',
      author:'DOROTHEA LANGE',
    },
  },
  {
    id:'fn-03', name:'Silver Screen', category:'film-noir',
    colors:{ bg:'#0c0c10', surface:'#14141e', text:'#e0dce8', accent:'#7070aa', muted:'#444455' },
    fonts:{ heading:F.mileast, body:F.raleway },
    pages:['cover','full-bleed','split-right','grid-4','text-spread','quote-page'],
    coverStyle:{ titleSize:'4.5rem', layout:'bottom-left', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.p1, img2:S.p5, img3:S.p4, img4:S.p2 },
    sampleTexts:{
      title:'SILVER\nSCREEN', subtitle:'CINEMA SERIES', tagline:'Frames per second, stilled',
      caption:'Between frames, the film is dark — between photographs, so is everything else',
      title2:'CINEMATIC', body:'The best photographs borrow from cinema\'s grammar. The establishing shot, the close-up, the reaction shot — all of these translate to still images that tell sequential stories.',
    },
  },
  {
    id:'fn-04', name:'Femme Fatale', category:'film-noir',
    colors:{ bg:'#0d0005', surface:'#1a0010', text:'#f5e8f0', accent:'#aa2060', muted:'#553545' },
    fonts:{ heading:F.elegist, body:F.spectral },
    pages:['cover','full-bleed','portrait-feature','window-strip','quote-page','editorial-4'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:true, titleStyle:'italic' },
    sampleImages:{ img1:S.p1, img2:S.p4, img3:S.p5, img4:S.p2 },
    sampleTexts:{
      title:'FEMME\nFATALE', subtitle:'PORTRAIT SERIES — VOL IV', tagline:'Power has always been feminine',
      name:'VICTORIA NIGHT', title2:'THE LEAD', body:'Photographer and subject in one. Night photographs herself as the women Hollywood forgot to fear — not the victim, not the love interest, not the moral — but the force that drives every frame.',
      quote:'I am not afraid of storms, for I am learning how to sail my ship.',
      author:'LOUISA MAY ALCOTT',
    },
  },
  {
    id:'fn-05', name:'Rain Shadow', category:'film-noir',
    colors:{ bg:'#080c10', surface:'#10161e', text:'#c8d0d8', accent:'#405060', muted:'#3a4550' },
    fonts:{ heading:F.cormorant, body:F.lato },
    pages:['cover','full-bleed','text-spread','masonry-3','quote-page','text-columns'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.l3, img2:S.p5, img3:S.p2, img4:S.l4 },
    sampleTexts:{
      title:'RAIN\nSHADOW', subtitle:'WET PLATE EDITION', tagline:'The city in water',
      caption:'Rain makes the world honest',
      title2:'WET STREETS', body:'Rain is the street photographer\'s best collaborator. It empties the frame of the unimportant, adds depth to every puddle, and makes every pedestrian a character in a story.',
      body1:'The wet street doubles everything. The sky comes down to meet the earth.',
      body2:'Umbrella compositions, reflections in standing water, the blur of wet glass — these are rain\'s gifts to the photographer willing to get cold.',
    },
  },

  // ══════════ STUDIO PORTFOLIO ════════════════════════════════════════════════

  {
    id:'sp-01', name:'Clean Portfolio', category:'portfolio',
    colors:{ bg:'#ffffff', surface:'#f5f5f5', text:'#111', accent:'#111', muted:'#aaa' },
    fonts:{ heading:F.josefin, body:F.lato },
    pages:['arch-cover','elegant-portrait','triple-portrait','grid-4','editorial-4','quote-page'],
    coverStyle:{ titleSize:'3.5rem', layout:'center', accentBar:false, letterSpacing:'0.25em' },
    sampleImages:{ img1:S.p2, img2:S.p5, img3:S.p1, img4:S.p4 },
    sampleTexts:{
      title:'PORTFOLIO', subtitle:'2026', tagline:'A selection of work from the past year. Portrait. Editorial. Documentary.',
      name:'IEM\nPHOTO CLUB', title:'SELECTED WORKS', year:'2026', label:'PORTFOLIO',
      subtitle2:'Photographer', label2:'PHOTOGRAPHY\nEDITORIAL\nPORTRAIT',
      label3:'STUDIO',
      st1:'The Subject', sb1:'Studio sessions that strip away artifice to reveal what the face actually holds.',
      st2:'Natural Light', sb2:'Morning window light — no modifier, no reflector, just the sun coming in.',
      st3:'Documentary', sb3:'Unposed, unlit, unretouched — the world as it presents itself.',
      quote:'The photograph itself doesn\'t interest me. I want only to capture a minute part of reality.',
      author:'HENRI CARTIER-BRESSON',
    },
  },
  {
    id:'sp-02', name:'Dark Portfolio', category:'portfolio',
    colors:{ bg:'#0d0d0d', surface:'#1a1a1a', text:'#f0f0f0', accent:'#e63946', muted:'#666' },
    fonts:{ heading:F.oswald, body:F.lato },
    pages:['bold-cover','portrait-feature','triple-portrait','masonry-3','quote-page','editorial-4'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:false, titleStyle:'normal' },
    sampleImages:{ img1:S.p5, img2:S.p2, img3:S.p4, img4:S.p1 },
    sampleTexts:{
      title:'SELECTED\nWORKS', subtitle:'DARKROOM\nEDITION', tagline:'Photography as practice. Not performance.',
      name:'THE PHOTOGRAPHER', title2:'SERIES I', year:'2026', label:'SERIES I',
      body:'These are the images that refused to be deleted. They insisted on existing.',
      quote:'The photograph itself doesn\'t interest me. I want only to capture a minute part of reality.',
      author:'HENRI CARTIER-BRESSON',
    },
  },
  {
    id:'sp-03', name:'Architect\'s Eye', category:'portfolio',
    colors:{ bg:'#f8f8f8', surface:'#ebebeb', text:'#111', accent:'#d44', muted:'#999' },
    fonts:{ heading:F.voyager, body:F.space },
    pages:['arch-cover','row-3','catalog-spread','grid-6','editorial-4','text-columns'],
    coverStyle:{ titleSize:'3rem', layout:'center', letterSpacing:'0.12em', accentBar:false },
    sampleImages:{ img1:S.l4, img2:S.l3, img3:S.l4, img4:S.l1, img5:S.l2, img6:S.l3 },
    sampleTexts:{
      title:'THE BUILT\nWORLD', subtitle:'ARCHITECTURAL STUDY', tagline:'Every building is a theory. The photograph tests it.',
      name:'THE BUILT\nWORLD', year:'2026', label:'PORTFOLIO',
      caption:'Architecture Series — 2026',
      body1:'Architecture photography is philosophy made visual. Every building is an argument about how space should be organized, how light should fall, how humans should move.',
      body2:'The camera that documents a building is not neutral. It chooses an angle, a time of day, a moment in the building\'s life. That choice is editorial.',
    },
  },
  {
    id:'sp-04', name:'Fashion Portfolio', category:'portfolio',
    colors:{ bg:'#fdf8f4', surface:'#ede8e0', text:'#1a1a1a', accent:'#8b4513', muted:'#999' },
    fonts:{ heading:F.bilderberg, body:F.lato },
    pages:['photo-book-cover','elegant-portrait','triple-portrait','split-right','editorial-4','quote-page'],
    coverStyle:{ titleSize:'3.5rem', layout:'center', titleStyle:'italic', accentBar:false },
    sampleImages:{ img1:S.p1, img2:S.p4, img3:S.p2, img4:S.p5 },
    sampleTexts:{
      title:'FASHION\nPORTFOLIO', subtitle:'EDITORIAL SERIES', tagline:'Clothes as language. Photography as translation.',
      name:'SOFIA REYES', title2:'THE SUBJECT', body:'Reyes began as a costume designer before discovering that the camera could capture what no garment could manufacture: the moment a person inhabits what they\'re wearing completely.',
      label:'Fashion Portfolio', title3:'Fashion Stories',
      st1:'The Garment', sb1:'A garment tells the story of the person who wears it — before they speak a word.',
      st2:'The Light', sb2:'Fashion photography lives and dies by the quality of the light on fabric.',
      st3:'The Attitude', sb3:'The pose reveals what the clothes alone cannot — the person inside them.',
      quote:'Fashion is the armor to survive the reality of everyday life.',
      author:'BILL CUNNINGHAM',
    },
  },
  {
    id:'sp-05', name:'Street Portfolio', category:'portfolio',
    colors:{ bg:'#111', surface:'#1e1e1e', text:'#ddd', accent:'#e63946', muted:'#666' },
    fonts:{ heading:F.oswald, body:F.montserrat },
    pages:['bold-cover','full-bleed','masonry-3','bold-dark','grid-4','text-columns'],
    coverStyle:{ titleSize:'5rem', layout:'bottom-left', accentBar:false, letterSpacing:'0.04em' },
    sampleImages:{ img1:S.l3, img2:S.p5, img3:S.p1, img4:S.l4 },
    sampleTexts:{
      title:'STREET\nPORTFOLIO', subtitle:'CITY SERIES — 2026', tagline:'The city as studio. Everyone a subject.',
      caption:'Shot on the streets. Never asked permission.',
      body1:'Street photography is the art of radical presence. You cannot plan it, manufacture it, or recreate it. You can only be there when it happens.',
      body2:'The decisive moment is not a technique. It is a state of attention so complete that the camera becomes an extension of consciousness.',
    },
  },

  // ══════════ NATURE & TRAVEL ═════════════════════════════════════════════════

  {
    id:'no-01', name:'Forest Walk', category:'nature',
    colors:{ bg:'#070e06', surface:'#0e1a0c', text:'#d8e8d0', accent:'#4a8040', muted:'#3a5535' },
    fonts:{ heading:F.cormorant, body:F.spectral },
    pages:['cover','full-bleed','captions-trio','row-3','catalog-spread','quote-page'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.l2, img2:S.l1, img3:S.l2, img4:S.l4, img5:S.l1, img6:S.l3 },
    sampleTexts:{
      title:'FOREST\nWALK', subtitle:'WOODLAND SERIES', tagline:'Into the cathedral of trees',
      caption:'Light in the forest is never quite the same twice',
      title2:'THE GREEN HOUR', body:'Early morning in a forest is a sacred thing. The light comes in sideways, picking out each individual leaf, catching the moisture in the air, making the ordinary world miraculous.',
      quote:'In every walk with nature, one receives far more than he seeks.',
      author:'JOHN MUIR',
    },
  },
  {
    id:'no-02', name:'Earth Tones', category:'nature',
    colors:{ bg:'#1a1208', surface:'#2a1e0e', text:'#f0e0c0', accent:'#c08840', muted:'#7a5830' },
    fonts:{ heading:F.dmserif, body:F.baskerville },
    pages:['cover','captions-trio','full-bleed','row-2','text-spread','quote-page'],
    coverStyle:{ titleSize:'3.8rem', layout:'bottom-left', accentBar:true, titleStyle:'italic' },
    sampleImages:{ img1:S.l1, img2:S.l2, img3:S.l4, img4:S.l3, img5:S.l1 },
    sampleTexts:{
      title:'EARTH\nTONES', subtitle:'DESERT SERIES', tagline:'Sand, stone and light',
      caption:'The desert teaches patience — nothing happens quickly here',
      title2:'THE LONG VIEW', body:'Desert landscapes reveal themselves slowly. The first photograph is always wrong. The second is closer. By the hundredth, you begin to understand what you are looking at.',
      quote:'The desert tells a different story every time one ventures into it.',
      author:'ROBERT MACFARLANE',
    },
  },
  {
    id:'no-03', name:'Ocean Blue', category:'nature',
    colors:{ bg:'#030810', surface:'#060e1a', text:'#d0e8f8', accent:'#2080c0', muted:'#305070' },
    fonts:{ heading:F.bodoni, body:F.raleway },
    pages:['cover','full-bleed','row-3','split-right','catalog-spread','photo-caption'],
    coverStyle:{ titleSize:'4.2rem', layout:'bottom-left', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.l1, img2:S.l2, img3:S.l3, img4:S.l4, img5:S.l1, img6:S.l2 },
    sampleTexts:{
      title:'OCEAN\nBLUE', subtitle:'SEASCAPE SERIES', tagline:'Water at its most honest',
      caption:'The ocean is never the same ocean twice',
      caption2:'Where land ends, the image begins',
    },
  },
  {
    id:'no-04', name:'Desert Sand', category:'nature',
    colors:{ bg:'#1a1208', surface:'#2a1e0c', text:'#f5e8c8', accent:'#d4a820', muted:'#806040' },
    fonts:{ heading:F.playfair, body:F.lato },
    pages:['cover','full-bleed','masonry-3','split-left','editorial-4','text-columns'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:true, titleStyle:'italic' },
    sampleImages:{ img1:S.l1, img2:S.l2, img3:S.l4, img4:S.l3 },
    sampleTexts:{
      title:'DESERT\nSAND', subtitle:'SAHARA SERIES — 2026', tagline:'Photographed at the edge of the world',
      caption:'Where the horizon is always further than it looks',
      title2:'THE DUNE', body:'Dunes are the desert\'s signature — their forms are the result of nothing more than wind and time, yet they achieve a sculptural quality that no human hand could manufacture.',
      body1:'The desert at noon is hostile to the camera. The light is too hard, too direct, too honest. You must wait.',
      body2:'At sunrise and sunset, the desert becomes something else entirely. The same sand that was brutal at midday becomes silk, gold, copper, fire.',
    },
  },
  {
    id:'no-05', name:'Golden Fields', category:'nature',
    colors:{ bg:'#100e00', surface:'#1e1a00', text:'#f8f0c8', accent:'#d4b820', muted:'#706030' },
    fonts:{ heading:F.cormorant, body:F.spectral },
    pages:['cover','full-bleed','row-3','split-right','quote-page','catalog-spread'],
    coverStyle:{ titleSize:'4rem', layout:'bottom-left', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.l2, img2:S.l1, img3:S.l4, img4:S.l3, img5:S.l2, img6:S.l1 },
    sampleTexts:{
      title:'GOLDEN\nFIELDS', subtitle:'HARVEST SERIES', tagline:'The season between summer and memory',
      caption:'Photographed in the dying light of September',
      title2:'THE HARVEST', body:'Autumn wheat fields have a music. The way the grain moves in the wind is not random — it is patterned, wave-like, almost rhythmic. The camera hears it.',
      quote:'Autumn is a second spring when every leaf is a flower.',
      author:'ALBERT CAMUS',
    },
  },

  // ══════════ ZINE & CASUAL ═════════════════════════════════════════════════

  {
    id:'zn-01', name:'Cut & Paste', category:'zine',
    colors:{ bg:'#ffffff', surface:'#f0f0f0', text:'#111', accent:'#e8242e', muted:'#888' },
    fonts:{ heading:F.abril, body:F.montserrat },
    pages:['cover','collage-5','split-left','grid-4','text-columns','full-bleed'],
    coverStyle:{ titleSize:'4.5rem', layout:'bottom-left', accentBar:true },
    sampleImages:{ img1:S.s1, img2:S.p3, img3:S.p5, img4:S.l3, img5:S.p1 },
    sampleTexts:{
      title:'CUT &\nPASTE', subtitle:'ZINE VOL. 01', tagline:'Made with scissors. Not software.',
      caption:'This zine was made by hand. All imperfections are intentional.',
      body1:'A zine is an act of defiance. It says: I don\'t need your permission to publish. I don\'t need your funding. I don\'t need your approval. I have scissors, a photocopier, and something to say.',
      body2:'The imperfections of zine culture are not failures — they are proof of humanity. Every crooked cut, every slightly off-center image, every typo that survived is evidence that a real person made this.',
    },
  },
  {
    id:'zn-02', name:'Street Zine', category:'zine',
    colors:{ bg:'#f5f0e0', surface:'#e8e0c0', text:'#1a1a0a', accent:'#1a1a0a', muted:'#808060' },
    fonts:{ heading:F.oswald, body:F.montserrat },
    pages:['cover','full-bleed','masonry-3','text-spread','grid-4','quote-page'],
    coverStyle:{ titleSize:'5rem', layout:'bottom-left', accentBar:false, letterSpacing:'0.04em' },
    sampleImages:{ img1:S.l3, img2:S.s1, img3:S.p5, img4:S.l4 },
    sampleTexts:{
      title:'STREET\nZINE', subtitle:'ISSUE #7 — HAND MADE', tagline:'The city speaks. We transcribe.',
      caption:'Shot on the street. Printed in the basement.',
      title2:'DISPATCH', body:'This is not a magazine. It is a conversation between photographers who walk the same streets at different hours and never meet, but recognize each other\'s photographs.',
    },
  },
  {
    id:'zn-03', name:'Handmade', category:'zine',
    colors:{ bg:'#faf5ec', surface:'#f0e8d8', text:'#2a1a0a', accent:'#8b4513', muted:'#9a7850' },
    fonts:{ heading:F.armelie, body:F.baskerville },
    pages:['cover','full-bleed','split-left','quote-page','row-3','editorial-4'],
    coverStyle:{ titleSize:'3.5rem', layout:'center', accentBar:false, titleStyle:'italic' },
    sampleImages:{ img1:S.d2, img2:S.d1, img3:S.l2, img4:S.p4 },
    sampleTexts:{
      title:'Handmade', subtitle:'A HAND-PRINTED COLLECTION', tagline:'Made slowly, with love, for nobody in particular',
      caption:'This photograph was developed in a bathroom. On purpose.',
      title2:'Slowly', body:'The handmade photograph carries something the digital image cannot: time. The time it took to develop, to print, to dry. The work is visible in the result.',
      quote:'The art of making is the art of caring.',
      author:'UNKNOWN',
    },
  },
  {
    id:'zn-04', name:'Urban Dispatch', category:'zine',
    colors:{ bg:'#111', surface:'#1e1e1e', text:'#ddd', accent:'#22dd88', muted:'#555' },
    fonts:{ heading:F.space, body:F.josefin },
    pages:['cover','full-bleed','grid-6','text-columns','row-3','editorial-4'],
    coverStyle:{ titleSize:'4.5rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.03em' },
    sampleImages:{ img1:S.l3, img2:S.l4, img3:S.s1, img4:S.p5, img5:S.l3, img6:S.l1 },
    sampleTexts:{
      title:'URBAN\nDISPATCH', subtitle:'CITY REPORT — SPRING 2026', tagline:'News from the ground',
      body1:'Urban photography is journalism without words. The image must do the work of the caption, the headline, and the editorial together.',
      body2:'The photographer who understands cities knows that every street corner tells three stories simultaneously. The job is to choose which one to freeze.',
    },
  },
  {
    id:'zn-05', name:'Night Market', category:'zine',
    colors:{ bg:'#08050f', surface:'#120a1e', text:'#f0e8f8', accent:'#a060f0', muted:'#4a3060' },
    fonts:{ heading:F.cocktail, body:F.lato },
    pages:['cover','full-bleed','collage-5','split-right','quote-page','grid-4'],
    coverStyle:{ titleSize:'3.2rem', layout:'bottom-left', accentBar:true },
    sampleImages:{ img1:S.d2, img2:S.d1, img3:S.p1, img4:S.l3, img5:S.p4 },
    sampleTexts:{
      title:'Night Market', subtitle:'FOOD & CULTURE ZINE', tagline:'Everything tastes better after midnight',
      caption:'The night market knows no closing time',
      title2:'After Midnight', body:'Between 11pm and 3am, the city\'s real personality emerges. The street food carts, the late-night conversations, the exhausted but alive.',
      quote:'Good food is the foundation of genuine happiness.',
      author:'ESCOFFIER',
    },
  },

  // ══════════ BRUTALIST ════════════════════════════════════════════════════════

  {
    id:'br-01', name:'Industrial', category:'brutalist',
    colors:{ bg:'#1a1a1a', surface:'#2a2a2a', text:'#e0e0e0', accent:'#e0e0e0', muted:'#666' },
    fonts:{ heading:F.bebas, body:F.montserrat },
    pages:['cover','full-bleed','grid-4','hero-text','text-columns','editorial-4'],
    coverStyle:{ titleSize:'6rem', layout:'bottom-left', accentBar:false, letterSpacing:'0.05em' },
    sampleImages:{ img1:S.l4, img2:S.l3, img3:S.l4, img4:S.l1 },
    sampleTexts:{
      title:'INDUSTRIAL', subtitle:'BRUTALIST SERIES', tagline:'Form follows function. Photography follows truth.',
      caption:'CONCRETE AND IRON — SERIES I',
      title2:'THE INDUSTRIAL EYE',
      body:'THE RAW MATERIAL OF ARCHITECTURE AND POWER',
      body1:'Brutalist architecture refuses to apologize for what it is. Concrete is concrete. Steel is steel. The photography that matches this honesty shows all of it.',
      body2:'No softening. No flattering angles. No magic hour. Just the material reality of things built to last, photographed in the kind of light that reveals rather than conceals.',
    },
  },
  {
    id:'br-02', name:'Raw Grid', category:'brutalist',
    colors:{ bg:'#ffffff', surface:'#f0f0f0', text:'#000000', accent:'#000000', muted:'#888' },
    fonts:{ heading:F.oswald, body:F.space },
    pages:['photo-book-cover','grid-6','row-3','catalog-spread','text-columns','grid-4'],
    coverStyle:{ titleSize:'4rem', layout:'center', letterSpacing:'0.1em', accentBar:false },
    sampleImages:{ img1:S.l4, img2:S.l3, img3:S.l4, img4:S.l1, img5:S.l2, img6:S.l3 },
    sampleTexts:{
      title:'RAW GRID', subtitle:'SYSTEMATIC STUDY', tagline:'One subject. Forty angles. One truth.',
      caption:'SYSTEMATIC DOCUMENTATION — 2026',
      body1:'The grid is the purest form of organization. It imposes no hierarchy, shows no favorites, makes no promises about importance. Every cell is equal until the image makes its case.',
      body2:'Working systematically means beginning without conclusions. You photograph everything and discover what matters later, in the editing, in the selection, in the sequencing.',
    },
  },
  {
    id:'br-03', name:'Power Type', category:'brutalist',
    colors:{ bg:'#111', surface:'#222', text:'#f5f500', accent:'#f5f500', muted:'#666' },
    fonts:{ heading:F.ncl, body:F.barlow },
    pages:['cover','full-bleed','hero-text','grid-4','text-columns','editorial-4'],
    coverStyle:{ titleSize:'6rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.03em' },
    sampleImages:{ img1:S.s1, img2:S.p3, img3:S.l3, img4:S.l4 },
    sampleTexts:{
      title:'POWER\nTYPE', subtitle:'BRUTALIST PRESS — ISSUE 01', tagline:'Large type means what it says.',
      title2:'MAXIMUM BOLD',
      body:'UNCOMPROMISING PHOTOGRAPHY FOR UNCOMPROMISING TIMES',
      body1:'Large type in graphic design is a commitment. It says: this is the most important thing. Everything else is secondary. The photograph underneath must be strong enough to share the frame.',
      body2:'The brutalist designer works with type as architecture — as load-bearing structure, not decoration. Every weight is a decision about power.',
    },
  },
  {
    id:'br-04', name:'Maximum Bold', category:'brutalist',
    colors:{ bg:'#ffffff', surface:'#f0f0f0', text:'#000', accent:'#e8242e', muted:'#888' },
    fonts:{ heading:F.transcity, body:F.josefin },
    pages:['cover','full-bleed','split-left','grid-4','hero-text','text-columns'],
    coverStyle:{ titleSize:'6rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.04em' },
    sampleImages:{ img1:S.p3, img2:S.s1, img3:S.p5, img4:S.l3 },
    sampleTexts:{
      title:'MAXIMUM\nBOLD', subtitle:'TYPOGRAPHIC EDITION', tagline:'TYPE IS THE MESSAGE.',
      caption:'PHOTOGRAPHY AS STATEMENT',
      title2:'THE STATEMENT',
      body:'THE IMAGE SPEAKS. THE TYPE SHOUTS.',
      body1:'There is a tradition of design that refuses to whisper. That says: here is the content, made as large as the space permits, competing with nothing, yielding to nothing.',
      body2:'The brutal thing about maximum bold typography is that it tells the truth about hierarchy. What is large is important. What is small is commentary.',
    },
  },
  {
    id:'br-05', name:'System Error', category:'brutalist',
    colors:{ bg:'#080808', surface:'#111', text:'#00ff41', accent:'#00ff41', muted:'#006620' },
    fonts:{ heading:F.space, body:F.voyager },
    pages:['cover','full-bleed','grid-6','text-columns','hero-text','editorial-4'],
    coverStyle:{ titleSize:'4.5rem', layout:'bottom-left', accentBar:true, letterSpacing:'0.04em' },
    sampleImages:{ img1:S.l3, img2:S.l4, img3:S.l1, img4:S.p5, img5:S.l3, img6:S.l2 },
    sampleTexts:{
      title:'SYSTEM\nERROR', subtitle:'DIGITAL BRUTALISM — v.2.0', tagline:'Photography is just light hitting sensors hitting code.',
      caption:'ALL DATA IS PHOTOGRAPHY — ALL PHOTOGRAPHY IS DATA',
      title2:'THE MACHINE SEES',
      body:'THE ALGORITHM HAS NO AESTHETICS. ONLY YOU DO.',
      body1:'Digital photography is the marriage of optics and mathematics. Every image is a file. Every file is a number. The art happens in spite of this, not because of it.',
      body2:'The brutalist digital photographer leans into the machine rather than fighting it. Uses its artifacts, its errors, its cold precision — and makes something human from the wreckage.',
    },
  },
]

// ── Helper: get by ID ─────────────────────────────────────────────────────────
export function getTemplateById(id) {
  return TEMPLATES.find(t => t.id === id) || null
}
